name: Build and Push Image to Aliyun

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: 'crpi-xxejudeah0w6sf1k.cn-shanghai.personal.cr.aliyuncs.com'
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and Push Image
        run: |
          IMAGE_NAME="crpi-xxejudeah0w6sf1k.cn-shanghai.personal.cr.aliyuncs.com/k8s-cicddemo/todo-app:v-${{ github.sha }}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME